-- ─────────────────────────────────────────────────────────────────────────
-- Collections AI — Borrower application schema
-- Runs automatically on first container start via /docker-entrypoint-initdb.d/
-- ─────────────────────────────────────────────────────────────────────────

-- ── borrowers ────────────────────────────────────────────────────────────
-- One row per borrower. Used by verify_borrower_identity tool.

CREATE TABLE IF NOT EXISTS borrowers (
    borrower_id             TEXT        PRIMARY KEY,
    full_name               TEXT        NOT NULL,
    loan_account_last4      CHAR(4)     NOT NULL,
    date_of_birth           DATE        NOT NULL,
    loan_id                 TEXT        NOT NULL UNIQUE,
    principal_amount        NUMERIC(14,2) NOT NULL,
    outstanding_amount      NUMERIC(14,2) NOT NULL,
    days_past_due           INTEGER     NOT NULL DEFAULT 0,
    loan_status             TEXT        NOT NULL DEFAULT 'overdue',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_borrowers_last4
    ON borrowers (loan_account_last4);

CREATE INDEX IF NOT EXISTS idx_borrowers_dob_year
    ON borrowers (EXTRACT(YEAR FROM date_of_birth));


-- ── borrower_financials ──────────────────────────────────────────────────
-- Self-reported financials captured during assessment.
-- Upserted by store_financial_data tool on every assessment run.

CREATE TABLE IF NOT EXISTS borrower_financials (
    borrower_id             TEXT        PRIMARY KEY REFERENCES borrowers(borrower_id),
    monthly_income          NUMERIC(14,2) NOT NULL,
    monthly_expenses        NUMERIC(14,2) NOT NULL,
    employment_status       TEXT        NOT NULL DEFAULT 'unknown',
    cash_flow_surplus       NUMERIC(14,2) GENERATED ALWAYS AS (monthly_income - monthly_expenses) STORED,
    recorded_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


-- ── borrower_behaviour_log ───────────────────────────────────────────────
-- Each classify_borrower_behaviour call appends a row.
-- Allows tracking behaviour drift across multiple contacts.

CREATE TABLE IF NOT EXISTS borrower_behaviour_log (
    id                      SERIAL      PRIMARY KEY,
    borrower_id             TEXT        NOT NULL REFERENCES borrowers(borrower_id),
    behaviour               TEXT        NOT NULL CHECK (behaviour IN ('cooperative','strategic','hostile')),
    confidence              NUMERIC(4,3),
    score_cooperative       INTEGER     DEFAULT 0,
    score_strategic         INTEGER     DEFAULT 0,
    score_hostile           INTEGER     DEFAULT 0,
    recommendation          TEXT,
    recorded_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_behaviour_borrower
    ON borrower_behaviour_log (borrower_id, recorded_at DESC);


-- ── settlement_documents ─────────────────────────────────────────────────
-- Documents generated by generate_settlement_document tool.

CREATE TABLE IF NOT EXISTS settlement_documents (
    id                      SERIAL      PRIMARY KEY,
    borrower_id             TEXT        NOT NULL REFERENCES borrowers(borrower_id),
    loan_id                 TEXT        NOT NULL,
    resolution_path         TEXT        NOT NULL,
    outstanding_amount      NUMERIC(14,2) NOT NULL,
    document_name           TEXT        NOT NULL,
    document_description    TEXT,
    issuer                  TEXT,
    is_required             BOOLEAN     NOT NULL DEFAULT TRUE,
    generated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_settlement_docs_borrower
    ON settlement_documents (borrower_id, generated_at DESC);


-- ─────────────────────────────────────────────────────────────────────────
-- Seed data — realistic test borrowers
-- ─────────────────────────────────────────────────────────────────────────

INSERT INTO borrowers
    (borrower_id, full_name, loan_account_last4, date_of_birth,
     loan_id, principal_amount, outstanding_amount, days_past_due, loan_status)
VALUES
    ('BRW-00000001', 'Rajesh Kumar',     '7823', '1985-03-15',
     'LN-2021-001', 100000.00,  85000.00,  90, 'overdue'),

    ('BRW-00000002', 'Priya Sharma',     '4412', '1990-07-22',
     'LN-2021-002', 250000.00, 210000.00, 120, 'overdue'),

    ('BRW-00000003', 'Mohammed Iqbal',   '9931', '1978-11-05',
     'LN-2022-003',  50000.00,  47500.00,  60, 'overdue'),

    ('BRW-00000004', 'Sunita Patel',     '1156', '1982-01-30',
     'LN-2020-004', 500000.00, 380000.00, 180, 'overdue'),

    ('BRW-00000005', 'Arjun Mehta',      '6674', '1995-09-10',
     'LN-2023-005',  75000.00,  72000.00,  45, 'overdue')
ON CONFLICT (borrower_id) DO NOTHING;
